### ISSUE TITLE
Compiling and managing icons

### ISSUE THREAD

**Issue by paulpopus** [localgovdrupal/localgov_theme#106]
In some themes you have a source folder for svgs that then get compiled and managed through sprites which can make it a lot easier for the developer and has caching improvements.

I'm happy to implement this, as I've done it before, is this a requirement?

@finnlewis @Adnan-cds @cjstevens78

**Comment by cjstevens78** [comment]
Hi @paulpopus the site uses font awesome for icons - I don't think we keep anything locally that would benefit from this.

**Comment by paulpopus** [comment]
Ok I'll close this and somebody can re-open if/when it becomes a requirement. Cheers!

**Comment by finnlewis** [comment]
Thanks @paulpopus @cjstevens78 ! Good to know.
