### ISSUE TITLE
Linting issue after upgrade to Gulp 4

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#108]
When I run 'gulp dev' its linting a file that doesn't exist 'assets/scss/lib/main.css'

![image](https://user-images.githubusercontent.com/11304107/96733080-f590a000-13b0-11eb-88c5-8e0a58b45023.png)

**Comment by paulpopus** [comment]
https://github.com/localgovdrupal/localgov_theme/pull/110 Should fix this by running the linter before SASS, which is why the files here are `.css` and not `.scss`.
