### ISSUE TITLE
Stylelint - linting rules and fixes related to flagged lint issues

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#111]
Style lint is now chucking out a large volume of issues, some need addressing some adding to the ignore list.

**Comment by andybroomfield** [comment]
In Drupal / Lando we can use phpcs / phix to resolve these. Is there a similar front end tool?

**Comment by cjstevens78** [comment]
PR for this https://github.com/localgovdrupal/localgov_theme/pull/113

@andybroomfield it was was related to stylelint automatically using linting rules it wasnt using previously. Ive updated accordingly.
