### ISSUE TITLE
Admin tools in the frontend

### ISSUE THREAD

**Issue by paulpopus** [localgovdrupal/localgov_theme#119]
I've opened this issue to discuss what the plan is around the admin tools we support in the frontend. This involves things like the view-edit-delete menu bar, masquerade and any other editor/admin specific tools that appear when viewing the site when logged in only.

In my experience in the past it was always a pain when dealing with issues in difference between markup and styling for the admin side in comparison to the logged out user side. One thing that I've found works reasonably well is to put all the admin tools in a separate region and give them a reasonable styling, this way it never interferes with content and any other layouts you may have on any given page.

Example:
![Screenshot from 2020-10-26 16-33-10](https://user-images.githubusercontent.com/35137243/97200322-fa869280-17a8-11eb-9c35-9e419fa2d84b.png)

Anyway, I'd like to know what the thinking around this is right now and what we plan to support out of the box. Things like quick edit can be annoying so it'd be good to discuss now.

FAO @finnlewis @cjstevens78 @andybroomfield @Adnan-cds

**Comment by andybroomfield** [comment]
Think first priority is to fix the markup so we actually support these tools.
Hopefully our default theme and the templates included with our modules do this now (The current BHCC site does not).

**Comment by finnlewis** [comment]
Interesting ideas - I'll have to come back to this and test a little to help me think about it.

**Comment by paulpopus** [comment]
I have some free time and could look at this as part of a more isolated piece of work, let me know what you think @finnlewis

**Comment by finnlewis** [comment]
Yes - let's make some headway - we needed to add a few things to Lambeth, like masquerade and responsive_preview.

Not sure about the local tasks in a separate region. That could mess with other things and they are sometimes used for things other than view / edit / delete. Can't think of an example off the top of my head.... oh login / reset password for example: https://beta.lambeth.gov.uk/user/login

**Comment by paulpopus** [comment]
Yeah for logins it will be different, it may or may not be an issue depending on who log ins. It's not entirely breaking the page just kind of weird. We can make exceptions per that page if it's important.

However I found that it makes a huge difference when theming as it's a lot easier to deal with varying layouts on different pages, sometimes the UX can suffer as you constantly try to fix those admin buttons breaking in different grids or content types. Then again I don't know how much it matters in this case if we're expecting the theme not to change much between sites.

**Comment by paulpopus** [comment]
Closing this as it's gotten stale and is not a problem right now as the admin blocks are styled.

![Screenshot from 2021-03-30 13-22-04](https://user-images.githubusercontent.com/35137243/112987749-f6e1a800-915a-11eb-9d45-4c8af79137eb.png)
