### ISSUE TITLE
Status message Twig template calls getStatusMessageWrapperClass which is part of bhcc_helper

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#12]
This seems to add a custom class depending on the status of the message. If this is needed it should be ported to localgov_core. If not the template and anywhere else that calls it needs to be refactored.

**Comment by ekes** [comment]
It only seems to be used there?

It also is just doing a string for string replacement. A lookup basically. Is there a more `Twig` way of doing this?

**Comment by ekes** [comment]
Grepping through the croydon code I only see this class and this method used in this template.
Also the second method getStatusMessageIconClass doesn't seem to be used at all.
