### ISSUE TITLE
Move Drupal Unit tests to PRs going into production only

### ISSUE THREAD

**Issue by paulpopus** [localgovdrupal/localgov_theme#120]
I propose that we move the automated Drupal unit tests from every PR to PRs that merge into production only. This is because they take way too long and are not always directly related to the theme.

The [last one](https://github.com/localgovdrupal/localgov_theme/runs/1309945172?check_suite_focus=true) that ran took 41.31 minutes to complete and sometimes that's way too long depending on the fix.

We can keep the other automated test that checks it compiles without errors as that one runs quickly enough.

Any objections? @finnlewis @Adnan-cds @cjstevens78

**Comment by finnlewis** [comment]
Interesting.
Maybe now that they will be running quicker, this will help. 
One option is that we only run the automated tests on merged to the release branch prior to tagging a release, as you suggest @paulpopus - but there were 60 commits in that last merge request so if tests do fail at that point, how much time would that take to unpick?
My instinct is that actually it is safer to keep the 'passes automated tests' gate on each PR and we just take that as part of the deal.

**Comment by Adnan-cds** [comment]
> My instinct is that actually it is safer to keep the 'passes automated tests' gate on each PR

I agree.  Not everyone runs tests in their development machines.  So we can't guarantee that an incoming PR will pass all the tests.  However, we can consider adding a [skip-ci type tag](https://circleci.com/docs/2.0/skip-build/#skipping-a-build) to commit messages if we want to avoid a long test run for some reason.

**Comment by paulpopus** [comment]
I'll close this now given that we've sped up the tests. Thanks for skip-ci tag, will be useful for non code changes.

**Comment by Adnan-cds** [comment]
> Thanks for skip-ci tag, will be useful for non code changes.

Sorry, I have not been clear enough :( we haven't actually implemented it, so I was just proposing perhaps we can do so. Thankfully, many other people have shared their Github actions code for this which should make it easy to implement.  Two examples:
- https://timheuer.com/blog/skipping-ci-github-actions-workflows/
- https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
