### ISSUE TITLE
Feeding back changes into localgov_theme as the localgov_croydon theme work progresses

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#124]
- Set base header sizes to custom size rather than bootstrap calc setting
- Finesse the .btn class inc remove unwanted inherited bootstrap attributes and take off rounded corners
- Guides navigation alignment of arrow icon
- Service pages allow for use of h3 or h2 headers
- Bigger gap below the breadcrumb

**Comment by keelanfh** [comment]
Closing as this is deprecated
