### ISSUE TITLE
Extend theme to accomodate localgov_subsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_theme#128]
I've created a new repo localgov_subsites, which both renames the localgov_campaigns and extends with more flexible banners and child pages, functionality coming from the Lambeth Council implementation.

We will need to do some theme work to allow this work to be visible on a default install.

I'll add some screenshots and 

The install now works and can be tested from https://github.com/localgovdrupal/localgov/tree/feature/156-subsites-replace-campaigns 

Or you can just install https://github.com/localgovdrupal/localgov_subsites without installing localgov_campaigns.

**Comment by keelanfh** [comment]
Closing as deprecated
