### ISSUE TITLE
WSOD when viewing revisions

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#132]
`Call to a member function bundle() on string in localgov_theme_theme_suggestions_alter()`

This happens when viewing a revision of a node.
### Steps to reproduce.
1. Go to an existing node.
2. Create a new revision.
3. Go to the revisions tab
4. Click the previous revision.

### What should happen
Preview page of the old revision

### What actually happens
WSOD with error message.

Debugging found this is because the node component of the url is just the NID, not the full node object.
Fix should be to check if its an int, and then load the node.

**Comment by paulpopus** [comment]
Has this been resolved? I couldn't replicate it on a fresh install.

**Comment by Adnan-cds** [comment]
> Has this been resolved?

Nah.  I have some code that avoids this in the Croydon codebase, but there is a simpler solution which Andy has hinted above.  But I haven't got to that yet.

**Comment by paulpopus** [comment]
@Adnan-cds I can have a look if you can let me know how to replicate it

**Comment by Adnan-cds** [comment]
> I can have a look if you can let me know how to replicate it

Sorry Paul, I don't have anything more to add to Andy's reproduction steps :(  I know that the PHP exception comes from [localgov_theme_theme_suggestions_alter()](https://github.com/localgovdrupal/localgov_theme/blob/1176e240aee6dd20b16a381d5e928f0fa1198123/localgov_theme.theme#L141) when it tries to determine the node bundle assuming that ```$node``` is a node object.  This is true most of time but not when you are viewing a node revision where ```$node``` is a node id.  [localgov_theme_preprocess_html()](https://github.com/localgovdrupal/localgov_theme/blob/1176e240aee6dd20b16a381d5e928f0fa1198123/localgov_theme.theme#L16) faces a similar situation but gracefully navigates it.

**Comment by andybroomfield** [comment]
@paulpopus try enabling localgov_demo to get some demo content and then create a new revision. 
Now trying to view the old revision will demonstrate the error.
