### ISSUE TITLE
Contrast on mega menu during hover state

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#134]
The colour contrast needs improving on the hover state (on at least the mega menu)

<img width="1241" alt="Screenshot 2020-11-20 at 9 55 24 am" src="https://user-images.githubusercontent.com/1467480/99786670-adcb7880-2b16-11eb-9255-1fe83ef4c56b.png">

**Comment by keelanfh** [comment]
@msayoung

**Comment by danchamp** [comment]
This theme is deprecated, closing.
