### ISSUE TITLE
Change the BS breakpoint on Step by Step pages to 'md'

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#137]
Between 576 and 728 the step by step menu should fill the page width - change : `<div id="sidebar-second" class="column sidebar col-sm-4">` to `<div id="sidebar-second" class="column sidebar col-md-4">`

**Comment by cjstevens78** [comment]
PR for this: https://github.com/localgovdrupal/localgov_theme/pulls

**Comment by paulpopus** [comment]
Closing this as it looks to be fixed in the PR!
