### ISSUE TITLE
Review tooling and asset compiling

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#17]
We want to leave compiled assets in the theme so that the site looks okay when the site is initially installed.
At the moment gulp compiles assets in the `src` directory and puts them in a `dist` directory. Does this sort of layout make sense if we're committing compiled assets; it seems to be duplicating fonts, images and JS files.
Perhaps it would be easier to have a `sass` directory and use gulp to compile this into the `css` directory. Leaving the fonts, images and JS files in place. Unless we want to do some processing of these files?

**Comment by stephen-cox** [comment]
@cjstevens78 Just flagging this as something we should resolve sooner rather than later. If we re-organise the theme layout once a number of people are working on the theme it could cause serious problems.

My proposal is to remove the `/src' and '/dest' directories and move their contents in the root of the theme, so the theme would look like:
- '/css' - compiled SASS
- '/fonts' - any fonts - although this won't be necessary if we're using fonts loaded from a CDN
- '/img' - images included with the theme
- '/js' - JavaScript included with the theme
- '/scss' - SASS files to be compiled with gulp
- '/templates' - Twig templates

If we go with this (or similar) layout we will need to update the gulp file and libraries included in the theme, along with any templates that load any assets directly.

What do you think?

**Comment by stephen-cox** [comment]
As part of this we also want to clean-up the libraries file [1] as there's stuff there which has been removed (font-face.css) or isn't being installed because we're adding compiled assets to the theme (bootstrap.min.js).

[1] https://github.com/localgovdrupal/localgov_theme/blob/master/localgov_theme.libraries.yml

**Comment by stephen-cox** [comment]
@cjstevens78 I'm planning on taking a look at this tomorrow unless you've already started? It will likely cause problems with any changes you're making to assets to let me know if this is going to be a problem.

**Comment by cjstevens78** [comment]
@stephen-cox sure no problem - i had got as far as creating a branch for it which i have pushed 17-theme-asset-compiling but hadnt actually started anything.. ill hold off on anything asset related for now

**Comment by stephen-cox** [comment]
OK - thanks @cjstevens78 - I will look at it now and pass it to you for review
