### ISSUE TITLE
Add fr to allowed units

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_theme#170]
The linting config doesn't currently allow fr as a CSS unit:

https://github.com/localgovdrupal/localgov_theme/blob/f1cd33c504ee9092fdfa632952643a7ff0ccc9d4/.stylelintrc#L36

The [fr unit](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#the_fr_unit) is really useful for flexible / responsive CSS grid layouts and it would be good to have it available to use in the theme.

[Browser support is excellent](https://caniuse.com/css-grid), and if we need to support IE11 there's a prefixed alternative syntax. 

@cjstevens78 @paulpopus @stephen-cox @andybroomfield @Adnan-cds @finnlewis Any objections / thoughts? I've used it in news but can take an alternative approach.

**Comment by paulpopus** [comment]
I think it got left out by chance, happy to add it as it makes sense!

**Comment by danchamp** [comment]
Thanks @paulpopus!

**Comment by cjstevens78** [comment]
no concerns here
