### ISSUE TITLE
What layouts do we want to standardise on?

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#19]
Looking at the Croydon and BHCC sites they appear to either use a single full-width main content area or a main content area with a right-hand sidebar.

Are there any pages using a left-hand sidebar? If not we could drop the sidebar_fist and sidebar_second content areas and  create a single sidebar_right content area.
We could then default set a default page template with a right-sidebar and allow content types to remove this if they should be displayed full width.

Thoughts?

**Comment by andybroomfield** [comment]
There are blocks defined for sidebar first on BHCC.
News search page block
https://new.brighton-hove.gov.uk/news/search?keys=test
and a directory entry
https://new.brighton-hove.gov.uk/directories/special-educational-needs-and-disability-support/amaze

Generally a good idea to keep themes flexible, left sidebars are a reasonably common feature on websites. Most Drupal themes use a conditional if to render them, and let the main content expand which I assume the new theme would do.

One issue our comms team ask for is that not all pages with heavy body text bleed full width so having a max width on the main body content if there is no sidebar is desirable.

**Comment by stephen-cox** [comment]
Thanks @andybroomfield I will assume a 3 column layout and see if we can set this so that the appropriate grid classes are added depending whether the sidebars have any content.

Limiting the width of a single full width column is an interesting problem because there will be landing pages which have no sidebar content but need to fill be full width and there are text pages that it's desirable not to be full width, but this should be handleable by specific content types.

**Comment by finnlewis** [comment]
Also related: https://github.com/localgovdrupal/localgov_theme/issues/18
