### ISSUE TITLE
Add Font Awesome to the theme

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#20]
Font Awesome is used for icons but these are all broken because the font files aren't being loaded.
Should we commit the font files or use a CDN?

**Comment by andybroomfield** [comment]
I think we use CDN, though an option to override or fallback would be nice.
We actully use the [fontawesome module](http://drupal.org/project/fontawesome) to handle this.

**Comment by cjstevens78** [comment]
The CDN link for font awesome (https://use.fontawesome.com/releases/v5.8.2/css/all.css) is controlled via admin in this location admin > config > content > fontawesome but this isnt showing in my localgov instance so perhaps the module Andy mentions above needs to be enabled?

**Comment by stephen-cox** [comment]
The Font Awesome module has not been installed. Is there a good reason for using this module over just adding the CDN and/or font files to a library in the theme?

If we decide to use the module it will need adding as a dependency to the localgov_core module.

**Comment by andybroomfield** [comment]
> The Font Awesome module has not been installed. Is there a good reason for using this module over just adding the CDN and/or font files to a library in the theme?
> 
> If we decide to use the module it will need adding as a dependency to the localgov_core module.

Its used for home page icons on BHCC site (and Croydon I assume) to allow content editors to decide which icons to use and some extra settings. 

<img width="1110" alt="Screenshot 2020-06-10 at 12 28 12 am" src="https://user-images.githubusercontent.com/1467480/84210784-89706800-aab1-11ea-9a5a-473c18902251.png">

I would suggest if the CDN is the preferred route to check if the module is enabled first and then use the CDN if no other options available. Or allow a custom theme setting to either use CDN, local installed one, or none (and rely on an appropriate module).

**Comment by stephen-cox** [comment]
From our discussions yesterday it seems the Drupal Font Awesome Icons module (https://www.drupal.org/project/fontawesome) will be a requirement for quite a bit of upcoming stuff. This being the case, it should be enabled and configured in the localgov_core module.

I've added an issue for this here: https://github.com/localgovdrupal/localgov_core/issues/13
