### ISSUE TITLE
Update README to explain localgov_base

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_theme#202]
Now that we are mainly focussing on localgov_base, we shoud explain this in the README here. 

Probably need to 

- [x] Update the README.md to say something like "This theme is deprecated. It won't be further updated."
- [x] Add lifecycle key to the info.yml file. See https://www.drupal.org/node/3215042

**Comment by andybroomfield** [comment]
Just to confirm this theme is deprecated now? So we can action this.

**Comment by finnlewis** [comment]
Note: we should also disable dependabot alerts for this project.

**Comment by finnlewis** [comment]
@cjstevens78 @Adnan-cds @MattOz-CDS I've updated the README to highlight that this theme is no longer maintained or recommended. I hope that's not controversial at all but let me know if we need to say anything else in the README.

I'll also look at adding the lifecycle key to the info.yml file ( https://www.drupal.org/node/3215042 )

**Comment by finnlewis** [comment]
Also @cjstevens78 @Adnan-cds @MattOz-CDS this theme is triggering repeated dependabot alerts, see: https://github.com/localgovdrupal/localgov_theme/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies 

Are you still using this theme at all?

Should we: 

1. merge PRs created by dependabot?
2. unpublish this theme completely?

**Comment by cjstevens78** [comment]
@finnlewis yes we're still using localgov_theme so option 1 for the time being - we will be off it soon - ill update when we have moved over.

**Comment by Adnan-cds** [comment]
> Should we:
> 1. merge PRs created by dependabot?

Yes, please.

**Comment by keelanfh** [comment]
I'll close this as the original task has been completed. There are dependabot alerts but nobody has merged, which suggests people haven't been interested in doing so. See also #220
