### ISSUE TITLE
Remove override.css

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#21]
This file just seems to be a collection of CSS tweaks targetting Croydon specific markup. If things are relevant to a generic theme they should be moved into the appropriate SASS file.

**Comment by cjstevens78** [comment]
There's some rogue bits and bobs in here that i'll split out into sass however, at the top of this file we have styling that relates to the 'admin' section of the site, mainly for styling the page editing toolbar. Seeing as this doesnt relate to the theme I wonder if its possible to extract this entirely from the theme folder and place its somewhere else?

**Comment by stephen-cox** [comment]
I think the plan is to have our own admin theme; even if this is just a sub-theme of Claro with some tweaks. There's an issue with not a lot on it for this here: https://github.com/localgovdrupal/localgov/issues/20

**Comment by cjstevens78** [comment]
I have remembered why we had that styling in there for admin .. the 'block' that the toolbar sits inside can only be targeted by the ID it is given which outputs differently for each instance of the site... for example the croydon one has the ID 'block-croydon-local-tasks' whereas the one for localgov is 'block-localgov-theme-local-tasks' ... I would suggest we include a custom class and target that instead.

**Comment by andybroomfield** [comment]
We have this in BHCC too. Its mostly for the local tasks which has been a long bug bear for when we set up micro sites with a child theme.
I think it originally came about as the BHCC site has a separate mark up repo and Drupal specific styles got added here.

**Comment by stephen-cox** [comment]
Closed with https://github.com/localgovdrupal/localgov_theme/pull/29
