### ISSUE TITLE
Styling services pages

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_theme#25]
Issue to track styling wash of all services pages and field components.

**Comment by stephen-cox** [comment]
This issue is blocked until this pull request is resolved: https://github.com/localgovdrupal/localgov_services/pull/48

**Comment by finnlewis** [comment]
PR https://github.com/localgovdrupal/localgov_services/pull/48 has now been merged.

**Comment by stephen-cox** [comment]
Elements are now all displaying and there's default content for this in the localgov_demo module, so the styling is ready for tidying up.

**Comment by cjstevens78** [comment]
Quick write up of issues I had getting the services content to show up in my local via the localgov_demo module and the steps taken thanks to @stephen-cox 

I enabled the module using 

```
lando drush en localgov_demo
```

This brought up an SQL error about ‘duplicate keys’

I then did a wipe and reimport using

```
lando drush si localgov --yes && lando drush en localgov_demo --yes && lando drush uli
```

The content still didnt show after this so I ran

```
 composer update --no-cache
```

The content still didnt show … at this point I switched from the theme folder to the root (im not sure if this is of any relevance). 

Then I ran:
```
git pull
rm -fr web/modules
rm -fr web/profiles
rm -fr web/themes
composer cc
composer update --no-cache
```
Then .. again ran 

```
lando drush si localgov --yes && lando drush en localgov_demo --yes && lando drush uli
```

After this, the content showed up in the site.
