### ISSUE TITLE
Chris and Dave to chat about consistency of design > theme coupling of Bootstrap

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_theme#26]

**Comment by cjstevens78** [comment]
I spoke with Dave. He has written a 'why we chose bootstrap' section in the croydon design system here: https://new.croydon.gov.uk/design-system/front-end-framework/bootstrap-css-framework ... he is also going to look into how best to distribute his 'base responsive accessible templates' he setup which are a set of templates that purely set out the layout of each template without any 'design' involved.
