### ISSUE TITLE
References to BHCC library in theme

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#32]
There are references to BHCC libraries within the theme that are causing failures.
eg. in misc/eck-entity--alert-banner.html.twig has
````
{{ attach_library('bhcc_alert_banner/alert_banner') }}
````
Whilst long term aim is to move these into modules, we should remove references / change them to localgov equivilents in the short term.

**Comment by paulpopus** [comment]
Closing issue as this has been resolved!
