### ISSUE TITLE
Review Croydon Bootstrap documentation

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#35]
There are a number of PDFs that contain Croydon specific styling information; https://github.com/localgovdrupal/localgov_theme/tree/master/documentation

Are these needed? If so, they should be rewritten for a generic theme.

**Comment by paulpopus** [comment]
If someone from Croydon can chime in on this, I'm happy to remove the PDFs which aren't that accessible anyway and merge any info into the Docs.
@andybroomfield @Adnan-cds ?

**Comment by Adnan-cds** [comment]
Copying @cjstevens78

**Comment by stephen-cox** [comment]
I'm closing this as it's no longer relevant.
