### ISSUE TITLE
Skeleton base theme as common ancestor

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_theme#45]
Issue to track creation of a 'skeleton' base theme.

From meeting with Microserve and tech team, Microserve poated this doc: 

https://docs.google.com/drawings/d/1n1vJ-vFgKZU-S5elK4S6WcAR5BWfwxPugee3xRKT0dU/edit

In sprint planning, we agreed to try this approacch, althogh we note that we're not too sure what will end up in the skeleton theme.

Sugegsted name: localgov_skeleton

To include: not much at the moment... potentially 
 - preprocess functions, 
 - layout dscovery

**Comment by finnlewis** [comment]
Hi @robhmicroserve !

Just copying you into this issue... we discussed in our sprint planning and @cjstevens78 is planning to get this in place this sprint, perhaps with some input from @stephen-cox 

Initially I think we'll just keep it simple for starters, as we're not sure what the most valuable commonality (preprocess / layouts / some templating? ) will be.

Do share any thoughts you have on this and I look forwad to catching up when I get back in a couple of weeks.

Cheers,

Finn

**Comment by stephen-cox** [comment]
@cjstevens78 There's now a skeleton base theme: https://github.com/localgovdrupal/localgov_skeleton

We will want to review what should move into it. My initial thoughts are not a lot. We may want to move the HTML and page Twig templates and any related preprocess functionality, but as things stand these will need editing to remove any Bootstrap layout classes.

The [feature/45-use-skeleton-theme]() branch and related merge request #50 just to the minimum to use the skeleton theme, but we can use them to move stuff into the skeleton theme if desired.
