### ISSUE TITLE
Do we want to commit the compiled assets?

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#5]
Croydon don't commit the complied assets, but this will add an extra build step and requires that the environment has node 10 with Gulp installed.

I think it's probably better to commit the compiled assets, but I have git ignored them for the time being.

**Comment by finnlewis** [comment]
I agree that compiled assets should be committed for an initial install. Makes sense for people to be able to see something nice when the fire it up.
