### ISSUE TITLE
[4d] Create LocalGov Drupal default theme

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#51]

**Comment by willguv** [comment]
- [ ] Review the templates to check for inconsistencies eg bootstrap classes

**Comment by cjstevens78** [comment]
the following pull request relating to this ticket has been merged: https://github.com/localgovdrupal/localgov_theme/pull/60

**Comment by willguv** [comment]
@cjstevens78 has this been deployed?

Can't see theming at https://localgovdrupal.agile.coop/schools/find-school/primary-infant-and-junior-schools

Thanks

**Comment by willguv** [comment]
@stephen-cox could you deploy this to UAT - thanks!

**Comment by finnlewis** [comment]
Chris still has a little to finish on direcotries, but closing this in favour of a fresh ticket @cjstevens78
