### ISSUE TITLE
[0.5d Chris] Remove transitions from expanding/ collapsing content

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#52]
Design Dave wrote:

As a rule of thumb we should not use transitions when collapsing / expanding content.

It's heavier to load and not good for accessibility.

We can use this general class:
.collapsing {
-webkit-transition: none;
transition: none;
display: none;
}

There may be some custom transitions like on the services menu that need to be removed.

**Comment by cjstevens78** [comment]
I have removed the transitions. The changes have been committed as part of  feature/51-default-theme
