### ISSUE TITLE
Stop Services menu expanding on page load

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#53]
Design Dave wrote

Is there anything we can do to stop the services menu loading expanded?

It's especially bad on mobile, it appears for a second then disappears on page load

See movie at https://trello-attachments.s3.amazonaws.com/5dd86a55299fe76799b1ab90/5f0f170f2cfb982a9b9708d1/0be5e464aad925ecaa044f36727292bb/movie.mp4

**Comment by cjstevens78** [comment]
This turned out to be the the services menu for desktop flashing up as the mobile menu loaded. I set it to be initially hidden and that fixed the problem. This has been checked in under issue #51

**Comment by finnlewis** [comment]
Done!
