### ISSUE TITLE
[0.5d Chris] Skip to main content link not working as expected

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#54]
1) When using a screen reader and navigating by keyboard, skip to main content appears after the cookie bar in the flow of the document. This is incorrect it should appear as the first item on the page and allow you to skip past the cookie bar, navigation, alert, big bang etc straight to the h1 in main

Ref: gov.uk

2) Skip to main content is not working correctly on some page templates.

See attached, on these templates it skips to an invisible 'group' in the page, not the main content or h1

**Comment by willguv** [comment]
![Screenshot_2020-07-15_at_18 02 31](https://user-images.githubusercontent.com/708140/90019623-97f02100-dca6-11ea-8803-0cca32b4919d.png)
![Screenshot_2020-07-15_at_18 03 03-1](https://user-images.githubusercontent.com/708140/90019632-9aeb1180-dca6-11ea-9c2a-642773d1afbc.png)
![Screenshot_2020-07-15_at_17 56 39](https://user-images.githubusercontent.com/708140/90019638-9b83a800-dca6-11ea-9752-c14b0db5c0b5.png)
![Screenshot_2020-07-15_at_18 11 27](https://user-images.githubusercontent.com/708140/90019639-9c1c3e80-dca6-11ea-8963-33159c254467.png)
![Screenshot_2020-07-15_at_18 03 03](https://user-images.githubusercontent.com/708140/90019643-9cb4d500-dca6-11ea-8823-d3e1c4c9100e.png)

**Comment by cjstevens78** [comment]
@willguv the localgov project currently doesnt have the cookie module which has blocked any progress with this. @Adnan-cds has suggested it would be straightforward to add in the one from Croydon but obviously that will need to be added to his workload if it is required.

**Comment by Adnan-cds** [comment]
The position of the cookie popup is actually dictated by the [EU Cookie compliance module](https://www.drupal.org/project/eu_cookie_compliance).  You can tell it to place the Cookie consent popup at the top or the bottom of the page.  This module even has a Screen-reader friendly option which, again, places the Cookie consent popup at the top of the page.  The idea being that you should be aware of the cookie content issue even before you jump to the main content.  I am [linking to the relevant Javascript code](https://git.drupalcode.org/project/eu-cookie-compliance/-/blob/8.x-1.x/js/eu_cookie_compliance.js#L130).

The popup has some screen-reader related issues though.  There is a [proposed fix for this](https://www.drupal.org/project/eu_cookie_compliance/issues/3152550)

If you really don't want this popup before the "Jump to main content" link, we have to write some Javascript to move it down.

FAO @willguv @cjstevens78

**Comment by willguv** [comment]
@Adnan-cds please write the code to cover off councils who set cookie bar to top - thanks

We agreed that this code lives in the LGD theme

**Comment by willguv** [comment]
@Adnan-cds I'm assuming this is not started - can you confirm? Thanks

**Comment by Adnan-cds** [comment]
> I'm assuming this is not started - can you confirm?

That's right.  I haven't done anything on this.

@willguv @cjstevens78

**Comment by finnlewis** [comment]
Moving this back to in progress as Adnan is working on it.

**Comment by Adnan-cds** [comment]
For reference, I have added the complete setup instructions in the [pull request](https://github.com/localgovdrupal/localgov_theme/pull/68#issuecomment-689693152)
