### ISSUE TITLE
Make sure Croydon breakpoints YAML is in LGD default theme

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#55]
@Adnan-cds wrote previously

As part of Responsive image configuration, I had add a YAML file that lists the available breakpoints. Drupal reads this file and allows us to use different types of images for different breakpoints. I have added this file to the "croydon" theme. So the Drupal configuration files now expect the "croydon" theme to be around for this functionality to work. The Brighton site of course doesn't use the "croydon" theme. So they cannot make use of our Responsive image configuration. We need to decide where we should keep this breakpoint definition file and similar other files.

**Comment by Adnan-cds** [comment]
The LocalGov theme already has a [breakpoint definition file](https://github.com/localgovdrupal/localgov_theme/blob/master/localgov_theme.breakpoints.yml), so this may have already been taken care off.

The localgov_media module also provides a similar [breakpoint definition](https://github.com/localgovdrupal/localgov_core/blob/master/modules/localgov_media/localgov_media.breakpoints.yml) which will be available to any site that will use this module.

**Comment by cjstevens78** [comment]
I have looked at this and would suggest that the theme breakpoint yaml file https://github.com/localgovdrupal/localgov_theme/blob/master/localgov_theme.breakpoints.yml @Adnan-cds mentions is sufficient. Suggest we just ask @stephen-cox to give this the once over and then close.

**Comment by stephen-cox** [comment]
The breakpoints definition in the theme and localgov_media module should be enough for responsive images to work as long as the image definitions are only kept in the theme and media module. Both the theme and media module are meant to be optional; in that a full LocalGov install will use them, but someone using a non-core module (e.g. Campaigns, Guides, Step by step), shouldn't be forced to install them.
