### ISSUE TITLE
Change naming convention for Start buttons on Service page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#56]
The new generic start button markup https://lbc-app-w-corpwebsite-p.azurewebsites.net/design-system/start-button.

Should be applied to this template https://lbc-app-w-corpwebsite-p.azurewebsites.net/adult-health-and-social-care.

Removing the btn-green naming convention. Not good for code sharing

**Comment by willguv** [comment]
<img width="963" alt="Screen_Shot_2020-04-15_at_16 06 27" src="https://user-images.githubusercontent.com/708140/90020486-d508e300-dca7-11ea-988e-478faf27dd0c.png">
<img width="555" alt="Screen_Shot_2020-04-15_at_16 06 36" src="https://user-images.githubusercontent.com/708140/90020489-d63a1000-dca7-11ea-8d1b-f59d5fa33a7f.png">
<img width="1086" alt="Screen_Shot_2020-04-16_at_12 56 48" src="https://user-images.githubusercontent.com/708140/90020496-d76b3d00-dca7-11ea-8a96-50c42059ecae.png">

**Comment by cjstevens78** [comment]
Changes for this have been made see : https://github.com/localgovdrupal/localgov_services/pull/74 & https://github.com/localgovdrupal/localgov_services/pull/73
