### ISSUE TITLE
[3d Chris timebox] Campaign tweaks - Implement - BREAK INTO CARDS

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#57]
BLOCKED https://github.com/localgovdrupal/localgov/issues/107

-----
See details on https://trello.com/c/dUN7Vklu

Too much to move over!

**Comment by willguv** [comment]
Two back end jobs in campaigns
- [ ] select style of banner
- [ ] adding logo to banner

@stephen-cox can you help, @cjstevens78 has details

-----
Separately, we need homepage to be complete on LGD in order to unpick dependency with campaigns

**Comment by stephen-cox** [comment]
@cjstevens78 If you can provide specs for this I can look at it, but don't have much time for dev work until Agile Collective rejoin the sprints after next week.

**Comment by cjstevens78** [comment]
@stephen-cox specs as follows:

We need to add the ability for the user to select a style of banner from two base options that can be configured further:

1/ Full width banner with optional logo - **centered** (full width background image with centered header text and optional logo) or **left aligned** (full width background image with left aligned header text and optional logo)
2/ Boxed off - (no background image, a boxed off, inline image on the rhs with left aligned text)

we have examples of the full width banners here http://csmdemo.uk/Croydon-Banners/banner-demo.html

**Comment by willguv** [comment]
@cjstevens78 port over styling and we'll discuss full width/ boxed off toggle on Weds 9th

**Comment by finnlewis** [comment]
@willguv will write new cards for any outsatnding items.
