### ISSUE TITLE
Reinstate the Design System as a module?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#59]
Discussion with Stephen and Ekes 

https://new.croydon.gov.uk/design-and-content-guidelines/bootstrap-4-theme

@andybroomfield suggests a separate module that councils can install or not

@clearspotmedia says the content changes a lot, and it might be difficult to keep up to date

@cjstevens78 suggests that we might be able to strip content back to only the essential components

**Comment by keelanfh** [comment]
Closing in favour of https://github.com/localgovdrupal/localgov/issues/566
