### ISSUE TITLE
Select Campaign banner style

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_theme#66]
@stephen-cox specs as follows:

We need to add the ability for the user to select a style of banner from two base options that can be configured further:

1/ Full width banner with optional logo - centered (full width background image with centered header text and optional logo) or left aligned (full width background image with left aligned header text and optional logo)
2/ Boxed off - (no background image, a boxed off, inline image on the rhs with left aligned text)

we have examples of the full width banners here http://csmdemo.uk/Croydon-Banners/banner-demo.html

**Comment by keelanfh** [comment]
Closing as this is deprecated
