### ISSUE TITLE
Remove dependency on bhcc_helper.current_page service

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_theme#7]
Many of the preprocess files in the localgov_theme.theme file load the current URL from the bhcc_helper.current_page service. This needs to be reviewed and the either the service moved to localgov_core or the current page will need to be looked up another way.

**Comment by ekes** [comment]
Wouldn't it make sense just to put the few relevant lines into the appropriate preprocess templates?

I copied the get node from route stuff into a base class of the Blocks that get generated for services https://github.com/localgovdrupal/localgov_services/commit/4bc6fbd3c52d53c36f7c65ee41d6d85a152585b2#diff-2b1c603abc6b7b97de9336b57e7a0835R53 This is the most complicated one and it's only a few lines of pretty standard Drupal code, so repeating it a few times seem fine?

**Comment by stephen-cox** [comment]
Agreed - I have done something similar: https://github.com/localgovdrupal/localgov_theme/blob/master/localgov_theme.theme#L19
