### ISSUE TITLE
Issue with icon display in main theme on https://localgovdrupal.agile.coop/

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_theme#70]
The font awesome icon display looks wrong when deployed to https://localgovdrupal.agile.coop/. Looks fine on my local instance but once in the test site there are widespread visual issues ... for example: icons in the footer touching text, social icons in the footer too small, services list chevrons misaligned and incorrect colour.

Ive not looked into this but some initial thoughts are that it could be related to the 'fontawesome' or 'localgov_demo' modules because I saw the issue locally when I enabled these two whilst working on something else.

**Comment by stephen-cox** [comment]
I see this problem on my local too.

It looks to be a problem with the Fontawesome module. As you mentioned in standup, changing the 'Font Awesome Method' to 'Web Fonts with CSS' fixes this.

The simplest solution would be to deploy some configuration to set this at install time. As the Fontawesome module is included with the localgov_paragraphs module we should add the a `fontawesome.settings.yml ` config to that module:

```
tag: i
method: webfonts
load_assets: true
use_cdn: true
external_svg_location: 'https://use.fontawesome.com/releases/v5.13.1/css/all.css'
use_shim: true
external_shim_location: 'https://use.fontawesome.com/releases/v5.13.1/css/v4-shims.css'
use_solid_file: true
use_regular_file: true
use_light_file: true
use_brands_file: true
use_duotone_file: true
external_svg_integrity: ''
allow_pseudo_elements: false
```

What do you think @cjstevens78

**Comment by cjstevens78** [comment]
@stephen-cox yes i ended up in this YML file but was unsure if I was in the right place - ill amend it.

**Comment by cjstevens78** [comment]
@stephen-cox can I just confirm, is this the location to add the config file : https://github.com/localgovdrupal/localgov_paragraphs/tree/master/config/install

**Comment by stephen-cox** [comment]
Hi @cjstevens78 - as the Fontawesome module is _not_ being enabled by default - it should go the localgov_paragraphs module, but rather than putting it in the `config/install` directory it should go in `config/optional` - you will have to create this directory.

**Comment by cjstevens78** [comment]
This is done - closing

**Comment by stephen-cox** [comment]
This is still a problem with new installs. Re-opening and assigning to me.
