### ISSUE TITLE
Create a localgov_theme_starterkit bundled with the theme

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#78]
Follow up to #76.
Some themes such as [Bootstrap Barrio](https://www.drupal.org/project/bootstrap_barrio) provide a starter kit theme to give a kick start on creating child themes.
(Eg. Copy the provided `themes/custom/localgov_theme/starterkit` and rename the required files) as a quicker way of getting a child theme up and running.

**Comment by finnlewis** [comment]
Sounds like @cjstevens78 is working on this

**Comment by cjstevens78** [comment]
PR for this https://github.com/localgovdrupal/localgov_theme/pull/114

**Comment by cjstevens78** [comment]
This is done - closing
