### ISSUE TITLE
Add separate style variable for button text colour

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#79]
The button colour currently uses preset text colours.
When creating a child theme, it may be that colours used for button colours have too low contrast with the chosen button background colour, or may be that a different colour is desired.
This happened with creating the BHCC demo theme as the link buttons where using the secondary colour (orange) for the text and a blue for the button.

eg. In localgov_theme `_buttons.scss`
````
.link-button {

  color: $white;

  &:hover {
    color: $white;
  }

  &:focus {
    span,
    &:after {
      color: $secondary;
    }
  }
````
Had to be overridden in localgov_theme_bhcc in `theme.scss`
`````
// Make sure the button colour is white.
.link-button,
.cta-action {
  color: $color-text-negative !important;
  span,
  &:after {
    color: $color-text-negative !important;
  }
}
````

It would be better to be able to set the link colour (and hover state) separately) eg. 
````
$link-button-secondary: $color-success;
$link-button-secondary-text: $color-text-negative;
$link-button-secondary-focus: $color-success-dark;
`````

**Comment by cjstevens78** [comment]
PR raised for this https://github.com/localgovdrupal/localgov_theme/pull/93

**Comment by cjstevens78** [comment]
merged
