### ISSUE TITLE
Anchor link colour should have its own variable

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#80]
Currently, the theme uses the variable for the primary colour as the link colour, but this may be different for child themes. 
It would be preferable to have a separate addressable variable.
In localgov_theme_bhcc this is done with
````
.page a {
  color: $color-link !important;
}
````

**Comment by cjstevens78** [comment]
I have amended this .. PR here: #81

**Comment by cjstevens78** [comment]
merged
