### ISSUE TITLE
The logo should use Drupals logo feature

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_theme#95]
Currently this is a fixed place holder image (used to be a logo).

How its handled at BHCC
`<img class="img-fluid" src="{{ logopath }}" alt="Home Brighton and Hove City Council" />`

See #61 

<img width="1247" alt="Screenshot 2020-10-12 at 5 47 42 pm" src="https://user-images.githubusercontent.com/1467480/95771766-85e52b80-0cb3-11eb-98ea-4bcb517e089f.png">

**Comment by cjstevens78** [comment]
Hi @andybroomfield I left the code in the page commented out for future use in header.html.twig: `   
      <a class="navbar-brand" href="/" title="LocalGov homepage">
        
        <img class="img-fluid" src="https://place-hold.it/180x100&fontsize=23" alt="LocalGov Logo" /> 
      </a>`

**Comment by andybroomfield** [comment]
Thanks @cjstevens78 just flagging these up either for work or if anyone wants to take this on.
